- hosts: all
  become: true

  tasks:
    - name: Gather server facts
      server_facts:
      become_user: cloak

    - name: Install letsencrypt
      apt: name=letsencrypt

    - name: Enable inbound HTTP
      command: /sbin/iptables -I INPUT 5 -p tcp --dport http -j ACCEPT
      ignore_errors: yes

    - name: Acquire certificate
      command: 'letsencrypt {% if letsencrypt_staging|default("no")|bool %}--staging{% endif %} --non-interactive --email {{ansible_local.cloak.config.email}} --agree-tos certonly -d {{cloak_fqdns|join(" -d ")}} --expand --standalone --standalone-supported-challenges http-01'

    - name: Disable inbound HTTP
      command: /sbin/iptables -D INPUT -p tcp --dport http -j ACCEPT
      ignore_errors: yes
